### PR TITLE
Update sha384 hash

### PR DESCRIPTION
**Pull request by sebastinez**
I'm relatively new to the GitHub Actions, and I couldn't test it because it didn't took my fork as a working GitHub Action..

I updated the Dockerfile with the corresponding sha384 hash from https://getcomposer.org/download/ to try fix the issue #1 

The shown error message is:
```
Installer corrupt
```

### CODE REVIEW

**Comment by sebastinez** [comment]
So I successfully managed to make an own GitHub Action run to lint PHP based on yours and with a different hash it worked
Here the logs:
https://github.com/sebastinez/php-lint-action/pull/6/checks?check_run_id=207270558

**Comment by sebastinez** [comment]
@michaelw90 any news about merging this pull request? Your GitHub Action as is, does not work.. Please consider this pull request to restore the functionality of your GitHub Action..

**Comment by AricStewart** [comment]
I just duplicated your efforts. :) but maybe another pull request will get some action.

**Comment by laurentksh** [comment]
@michaelw90  Can we get an update ?

**Pull request closed without merging**
